export const COMMENT_SET_VALUE = 'COMMENT_SET_VALUE';
export const COMMENT_CREATE = 'COMMENT_CREATE';
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_SHOWMORE_ITEM = 'COMMENT_SHOWMORE_ITEM';
export const COMMENT_SHOWMORE_HIDEALL = 'COMMENT_SHOWMORE_HIDEALL';